MIN_CONTOUR_AREA_FRACTION = 0.01

ORB_N_FEATURES = 1000
ORB_SCALE_FACTOR = 1.2
ORB_N_LEVELS = 8

MIN_MATCH_COUNT = 8
RANSAC_REPROJ_THRESHOLD = 3.0
MIN_INLIER_RATIO = 0.10

SCALE_MIN = 0.5
SCALE_MAX = 2.0

DILATION_KERNEL_SIZE = 7
HIGH_CONFIDENCE_THRESHOLD = 0.80
COVERAGE_THRESHOLD = 0.85
